'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Bell, CarFront, CheckCircle2, ChevronDown, FileCheck2, FileText, Gauge, Menu, MoreHorizontal, Plus, Search, Settings, ShieldCheck, Upload, X } from 'lucide-react';

type Document = { id: number; name: string; type: string; plate: string; vehicle: string; expirationDate: string; fileName?: string | null };
const demoDocuments: Document[] = [
  { id: 1, name: 'Permiso de circulación', type: 'Permiso', plate: 'LKPD-42', vehicle: 'Mazda CX-5 2022', expirationDate: '2026-09-05', fileName: 'permiso-circulacion.pdf' },
  { id: 2, name: 'Revisión técnica', type: 'Revisión', plate: 'LKPD-42', vehicle: 'Mazda CX-5 2022', expirationDate: '2026-09-18', fileName: 'revision-tecnica.pdf' },
  { id: 3, name: 'SOAP', type: 'Seguro', plate: 'LKPD-42', vehicle: 'Mazda CX-5 2022', expirationDate: '2026-10-12', fileName: 'soap-2026.pdf' },
  { id: 4, name: 'Padrón vehicular', type: 'Registro', plate: 'LKPD-42', vehicle: 'Mazda CX-5 2022', expirationDate: '2028-03-20', fileName: 'padron.pdf' },
];
const dateFormat = new Intl.DateTimeFormat('es-CL', { day: '2-digit', month: 'short', year: 'numeric' });
function daysUntil(date: string) { const today = new Date(); today.setHours(0, 0, 0, 0); return Math.ceil((new Date(`${date}T12:00:00`).getTime() - today.getTime()) / 86400000); }
function statusFor(date: string) { const days = daysUntil(date); if (days < 0) return { label: 'Vencido', tone: 'red' }; if (days <= 15) return { label: `Vence en ${days} días`, tone: 'orange' }; if (days <= 45) return { label: `Vence en ${days} días`, tone: 'yellow' }; return { label: 'Vigente', tone: 'green' }; }

export default function Home() {
  const [documents, setDocuments] = useState<Document[]>(demoDocuments);
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState<'all' | 'soon' | 'current'>('all');
  const [showForm, setShowForm] = useState(false);
  const [mobileNav, setMobileNav] = useState(false);
  const [savedMessage, setSavedMessage] = useState('');

  useEffect(() => { fetch('/api/documents').then((r) => r.ok ? r.json() : Promise.reject()).then((data: Document[]) => data.length && setDocuments(data)).catch(() => undefined); }, []);
  const filtered = useMemo(() => documents.filter((d) => `${d.name} ${d.type} ${d.vehicle} ${d.plate}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || (filter === 'soon' ? daysUntil(d.expirationDate) <= 45 : daysUntil(d.expirationDate) > 45))), [documents, filter, query]);
  const soon = documents.filter((d) => daysUntil(d.expirationDate) <= 45).length;
  const current = documents.length - soon;

  async function addDocument(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const formData = new FormData(event.currentTarget);
    const optimistic: Document = { id: Date.now(), name: String(formData.get('name')), type: String(formData.get('type')), vehicle: String(formData.get('vehicle')), plate: String(formData.get('plate')).toUpperCase(), expirationDate: String(formData.get('expirationDate')), fileName: (formData.get('file') as File)?.name || null };
    setDocuments((items) => [optimistic, ...items]); setShowForm(false); setSavedMessage('Documento guardado correctamente'); window.setTimeout(() => setSavedMessage(''), 3500);
    try { const response = await fetch('/api/documents', { method: 'POST', body: formData }); if (response.ok) { const saved = await response.json() as Document; setDocuments((items) => items.map((item) => item.id === optimistic.id ? saved : item)); } } catch { /* Local preview remains usable. */ }
  }

  return <main className="min-h-screen bg-[#f4f3ef] text-[#17231d]">
    <header className="sticky top-0 z-30 flex h-20 items-center justify-between border-b border-[#dfe1dc] bg-[#f8f7f3]/95 px-5 backdrop-blur md:px-9">
      <div className="flex items-center gap-3"><button aria-label="Abrir menú" className="mr-1 rounded-xl p-2 hover:bg-black/5 lg:hidden" onClick={() => setMobileNav(true)}><Menu size={22} /></button><div className="grid size-10 place-items-center rounded-xl bg-[#183f33] text-white shadow-sm"><CarFront size={22} /></div><div><p className="text-lg font-bold leading-none tracking-[-.03em]">ReadyCar</p><p className="mt-1 text-[10px] font-semibold uppercase tracking-[.18em] text-[#718078]">Documentos al día</p></div></div>
      <div className="flex items-center gap-2"><button className="relative grid size-10 place-items-center rounded-xl border border-[#d9ddd7] bg-white text-[#526159]" aria-label="Notificaciones"><Bell size={19} /><span className="absolute right-2 top-2 size-2 rounded-full bg-[#ec703b] ring-2 ring-white" /></button><div className="ml-1 hidden items-center gap-3 rounded-xl border border-[#d9ddd7] bg-white px-3 py-2 sm:flex"><div className="grid size-8 place-items-center rounded-lg bg-[#e2eee8] text-xs font-bold text-[#174434]">SM</div><div><p className="text-xs font-semibold">Sebastián</p><p className="text-[10px] text-[#738078]">Cuenta personal</p></div><ChevronDown size={14} /></div></div>
    </header>
    <div className="mx-auto flex max-w-[1500px]">
      <aside className={`${mobileNav ? 'fixed inset-0 z-40 flex' : 'hidden'} w-64 shrink-0 flex-col border-r border-[#dfe1dc] bg-[#f4f3ef] p-5 lg:sticky lg:top-20 lg:flex lg:h-[calc(100vh-80px)]`}><button aria-label="Cerrar menú" className="absolute right-4 top-4 p-2 lg:hidden" onClick={() => setMobileNav(false)}><X /></button><nav className="mt-12 space-y-2 lg:mt-0"><a className="flex items-center gap-3 rounded-xl bg-[#183f33] px-4 py-3 text-sm font-semibold text-white" href="#"><Gauge size={18} />Resumen</a><a className="flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-medium text-[#637068] hover:bg-white" href="#documentos"><FileText size={18} />Documentos <span className="ml-auto rounded-full bg-[#e1e3de] px-2 py-0.5 text-[10px]">{documents.length}</span></a><a className="flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-medium text-[#637068] hover:bg-white" href="#vehiculo"><CarFront size={18} />Mi vehículo</a><a className="flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-medium text-[#637068] hover:bg-white" href="#"><Bell size={18} />Alertas</a></nav><div className="mt-auto rounded-2xl border border-[#dce2dc] bg-[#eaf0eb] p-4"><div className="mb-3 grid size-9 place-items-center rounded-xl bg-white text-[#275344]"><ShieldCheck size={19} /></div><p className="text-sm font-bold">Todo en un solo lugar</p><p className="mt-1 text-xs leading-5 text-[#68756e]">Tus documentos protegidos y disponibles cuando los necesites.</p></div><button className="mt-4 flex items-center gap-3 px-4 py-3 text-sm text-[#66736b]"><Settings size={18} />Configuración</button></aside>
      <section className="min-w-0 flex-1 px-5 py-8 md:px-10 md:py-10"><div className="mx-auto max-w-6xl">
        <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.16em] text-[#6d7c73]">Sábado, 29 de agosto</p><h1 className="text-3xl font-bold tracking-[-.045em] sm:text-4xl">Tu vehículo, siempre al día.</h1><p className="mt-2 text-sm text-[#69766f]">Controla tus documentos y anticípate a cada vencimiento.</p></div><button onClick={() => setShowForm(true)} className="flex h-11 items-center justify-center gap-2 rounded-xl bg-[#ed6e3b] px-5 text-sm font-bold text-white shadow-[0_8px_20px_rgba(237,110,59,.22)] hover:-translate-y-0.5"><Plus size={18} />Agregar documento</button></div>
        <div className="mt-8 grid gap-4 md:grid-cols-3">
          <Stat active={filter === 'all'} onClick={() => setFilter('all')} icon={<FileCheck2 size={20} />} value={documents.length} title="Documentos registrados" description="Vista completa de tu carpeta" kind="dark" />
          <Stat active={filter === 'soon'} onClick={() => setFilter('soon')} icon={<AlertTriangle size={20} />} value={soon} title="Próximos a vencer" description="Dentro de los siguientes 45 días" kind="orange" />
          <Stat active={filter === 'current'} onClick={() => setFilter('current')} icon={<CheckCircle2 size={20} />} value={current} title="Documentos vigentes" description="Sin acciones inmediatas" kind="green" />
        </div>
        <div id="documentos" className="mt-7 overflow-hidden rounded-2xl border border-[#dfe1dc] bg-white"><div className="flex flex-col gap-4 border-b border-[#e6e7e3] p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-bold tracking-tight">Mis documentos</h2><p className="mt-1 text-xs text-[#77827b]">Ordenados por fecha de vencimiento</p></div><label className="flex h-10 items-center gap-2 rounded-xl border border-[#dfe1dc] bg-[#fafaf8] px-3 focus-within:border-[#4d7668]"><Search size={16} className="text-[#879189]" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="w-full bg-transparent text-sm outline-none sm:w-52" placeholder="Buscar documento" /></label></div><div className="divide-y divide-[#ecece8]">{filtered.map((document) => <DocumentRow key={document.id} document={document} />)}{!filtered.length && <div className="px-5 py-14 text-center"><Search className="mx-auto text-[#9aa29d]" /><p className="mt-3 text-sm font-semibold">No encontramos documentos</p><p className="mt-1 text-xs text-[#7c8780]">Prueba con otra búsqueda o filtro.</p></div>}</div></div>
        <div id="vehiculo" className="mt-6 flex flex-col justify-between gap-5 rounded-2xl bg-[#dfe9e3] p-6 sm:flex-row sm:items-center"><div className="flex items-center gap-4"><div className="grid size-12 place-items-center rounded-xl bg-[#183f33] text-white"><CarFront /></div><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#64756b]">Vehículo principal</p><p className="mt-1 font-bold">Mazda CX-5 2022 · LKPD-42</p></div></div><p className="max-w-sm text-xs leading-5 text-[#627168]">Recibirás alertas en esta plataforma cuando un documento esté a 45, 15 y 5 días de vencer.</p></div>
      </div></section>
    </div>
    {showForm && <DocumentForm onClose={() => setShowForm(false)} onSubmit={addDocument} />}
    {savedMessage && <div role="status" className="fixed bottom-5 right-5 z-50 flex items-center gap-2 rounded-xl bg-[#183f33] px-4 py-3 text-sm font-semibold text-white shadow-xl"><CheckCircle2 size={18} />{savedMessage}</div>}
  </main>;
}

function Stat({ active, onClick, icon, value, title, description, kind }: { active: boolean; onClick: () => void; icon: React.ReactNode; value: number; title: string; description: string; kind: 'dark' | 'orange' | 'green' }) {
  const dark = kind === 'dark'; const selected = active ? (dark ? 'border-[#275747] bg-[#183f33] text-white shadow-lg' : kind === 'orange' ? 'border-[#e8b187] bg-[#fff5eb]' : 'border-[#9bc3ad] bg-[#eef8f2]') : 'border-[#dfe1dc] bg-white';
  return <button onClick={onClick} className={`rounded-2xl border p-5 text-left transition hover:-translate-y-0.5 ${selected}`}><div className="flex items-start justify-between"><div className={`grid size-10 place-items-center rounded-xl ${dark && active ? 'bg-white/12' : kind === 'orange' ? 'bg-[#fff0e5] text-[#de6531]' : 'bg-[#e8f0ec] text-[#245342]'}`}>{icon}</div><span className={`text-3xl font-bold ${dark && active ? '' : 'text-[#203028]'}`}>{value}</span></div><p className="mt-5 text-sm font-semibold">{title}</p><p className={`mt-1 text-xs ${dark && active ? 'text-white/60' : 'text-[#768179]'}`}>{description}</p></button>;
}

function DocumentRow({ document }: { document: Document }) { const status = statusFor(document.expirationDate); return <article className="grid gap-4 p-5 transition hover:bg-[#fafaf7] md:grid-cols-[1.5fr_1fr_1fr_auto] md:items-center"><div className="flex min-w-0 items-center gap-4"><div className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#edf1ee] text-[#315b4c]"><FileText size={20} /></div><div className="min-w-0"><p className="truncate text-sm font-bold">{document.name}</p><p className="mt-1 truncate text-xs text-[#7b857e]">{document.fileName || 'Sin archivo adjunto'} · {document.type}</p></div></div><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#909892]">Vehículo</p><p className="mt-1 text-sm font-semibold">{document.plate}</p><p className="text-xs text-[#7c8780]">{document.vehicle}</p></div><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#909892]">Vencimiento</p><p className="mt-1 text-sm font-semibold">{dateFormat.format(new Date(`${document.expirationDate}T12:00:00`))}</p><span className={`mt-1 inline-flex rounded-full px-2 py-1 text-[10px] font-bold status-${status.tone}`}>{status.label}</span></div><button className="grid size-9 place-items-center rounded-lg text-[#7a847e] hover:bg-[#eeefeb]" aria-label={`Opciones de ${document.name}`}><MoreHorizontal size={18} /></button></article>; }

function DocumentForm({ onClose, onSubmit }: { onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-[#10241c]/55 p-4 backdrop-blur-sm" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><form onSubmit={onSubmit} className="w-full max-w-lg rounded-3xl bg-[#fbfbf8] p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#78847c]">Nuevo registro</p><h2 className="mt-2 text-2xl font-bold tracking-tight">Agregar documento</h2></div><button type="button" aria-label="Cerrar" onClick={onClose} className="rounded-xl p-2 hover:bg-black/5"><X size={20} /></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="field sm:col-span-2">Nombre del documento<input name="name" required placeholder="Ej. Permiso de circulación" /></label><label className="field">Tipo<select name="type" defaultValue="Permiso"><option>Permiso</option><option>Revisión</option><option>Seguro</option><option>Registro</option><option>Otro</option></select></label><label className="field">Fecha de vencimiento<input name="expirationDate" type="date" required /></label><label className="field">Vehículo<input name="vehicle" required defaultValue="Mazda CX-5 2022" /></label><label className="field">Patente<input name="plate" required defaultValue="LKPD-42" /></label><label className="field sm:col-span-2"><span>Archivo <em>(opcional, máx. 10 MB)</em></span><span className="flex h-24 cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-[#bcc5bf] bg-white text-sm font-semibold text-[#557066]"><Upload size={18} />Subir PDF o imagen</span><input className="sr-only" name="file" type="file" accept="application/pdf,image/*" /></label></div><div className="mt-7 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-xl px-5 py-3 text-sm font-semibold hover:bg-black/5">Cancelar</button><button className="rounded-xl bg-[#183f33] px-5 py-3 text-sm font-bold text-white">Guardar documento</button></div></form></div>; }
